// Status
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';

// Account
export const ACCOUNT_ON = 'ACCOUNT_ON';
export const ACCOUNT_OFF = 'ACCOUNT_OFF';
export const ACCOUNT_CHECK_REQUEST = 'ACCOUNT_CHECK_REQUEST';
export const ACCOUNT_CHECK_SUCCESS = 'ACCOUNT_CHECK_SUCCESS';
export const ACCOUNT_CHECK_FAILURE = 'ACCOUNT_CHECK_FAILURE';
export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
export const ACCOUNT_LOG_IN_REQUEST = 'ACCOUNT_LOG_IN_REQUEST';
export const ACCOUNT_LOG_IN_SUCCESS = 'ACCOUNT_LOG_IN_SUCCESS';
export const ACCOUNT_LOG_IN_FAILURE = 'ACCOUNT_LOG_IN_FAILURE';
export const ACCOUNT_LOG_OUT_REQUEST = 'ACCOUNT_LOG_OUT_REQUEST';
export const ACCOUNT_LOG_OUT_SUCCESS = 'ACCOUNT_LOG_OUT_SUCCESS';
export const ACCOUNT_LOG_OUT_FAILURE = 'ACCOUNT_LOG_OUT_FAILURE';
export const ACCOUNT_RESET_PASSWORD_REQUEST = 'ACCOUNT_RESET_PASSWORD_REQUEST';
export const ACCOUNT_RESET_PASSWORD_SUCCESS = 'ACCOUNT_RESET_PASSWORD_SUCCESS';
export const ACCOUNT_RESET_PASSWORD_FAILURE = 'ACCOUNT_RESET_PASSWORD_FAILURE';

// Profile
export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE';
export const PROFILE_STATUS_REQUEST = 'PROFILE_STATUS_REQUEST';
export const PROFILE_STATUS_SUCCESS = 'PROFILE_STATUS_SUCCESS';
export const PROFILE_STATUS_FAILURE = 'PROFILE_STATUS_FAILURE';
export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAILURE = 'PROFILE_LOAD_FAILURE';
export const PROFILE_VOID = 'PROFILE_VOID';

// View
export const VIEW_LOAD_REQUEST = 'VIEW_LOAD_REQUEST';
export const VIEW_LOAD_SUCCESS = 'VIEW_LOAD_SUCCESS';
export const VIEW_LOAD_FAILURE = 'VIEW_LOAD_FAILURE';
export const VIEW_VOID = 'VIEW_VOID';

// Call
export const CALLS_VOID = 'CALLS_VOID';

// User
export const USERS_LOAD_REQUEST = 'USERS_LOAD_REQUEST';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAILURE = 'USERS_LOAD_FAILURE';
export const USERS_VOID = 'USERS_VOID';

// Post
export const POST_ADD = 'POST_ADD';
export const POST_EDIT = 'POST_EDIT';
export const POST_SAVE_REQUEST = 'POST_SAVE_REQUEST';
export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
export const POST_SAVE_FAILURE = 'POST_SAVE_FAILURE';
export const POSTS_LOAD_REQUEST = 'POSTS_LOAD_REQUEST';
export const POSTS_LOAD_SUCCESS = 'POSTS_LOAD_SUCCESS';
export const POSTS_LOAD_FAILURE = 'POSTS_LOAD_FAILURE';
export const POSTS_VOID = 'POSTS_VOID';

// Campaign
export const CAMPAIGN_ADD = 'CAMPAIGN_ADD';
export const CAMPAIGN_EDIT = 'CAMPAIGN_EDIT';
export const CAMPAIGN_SAVE_REQUEST = 'CAMPAIGN_SAVE_REQUEST';
export const CAMPAIGN_SAVE_SUCCESS = 'CAMPAIGN_SAVE_SUCCESS';
export const CAMPAIGN_SAVE_FAILURE = 'CAMPAIGN_SAVE_FAILURE';
export const CAMPAIGNS_LOAD_REQUEST = 'CAMPAIGNS_LOAD_REQUEST';
export const CAMPAIGNS_LOAD_SUCCESS = 'CAMPAIGNS_LOAD_SUCCESS';
export const CAMPAIGNS_LOAD_FAILURE = 'CAMPAIGNS_LOAD_FAILURE';
export const CAMPAIGNS_VOID = 'CAMPAIGNS_VOID';

// Lead
export const LEAD_ADD = 'LEAD_ADD';
export const LEAD_EDIT = 'LEAD_EDIT';
export const LEAD_SAVE_REQUEST = 'LEAD_SAVE_REQUEST';
export const LEAD_SAVE_SUCCESS = 'LEAD_SAVE_SUCCESS';
export const LEAD_SAVE_FAILURE = 'LEAD_SAVE_FAILURE';
export const LEADS_LOAD_REQUEST = 'LEADS_LOAD_REQUEST';
export const LEADS_LOAD_SUCCESS = 'LEADS_LOAD_SUCCESS';
export const LEADS_LOAD_FAILURE = 'LEADS_LOAD_FAILURE';
export const LEADS_VOID = 'LEADS_VOID';
